version: "3.4"

services:
  fastapis:
    image: tiangolo/uvicorn-gunicorn-fastapi:latest
    ports:
      - target: 80
        published: 8000
    deploy:
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.fastapis.rule=Host(`fastapi.tmktmk.domdom.burger`)"
        - "traefik.http.services.fastapis.loadbalancer.server.port=80"

    networks:
      - test_proxy

networks:
  test_proxy:
    external: true
