version: "3.4"

services:
  nginxs:
    image: nginx:latest
    ports:
      - target: 80
        published: 9000
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 2
      labels:
        - "traefik.enable=true"
        # - "traefik.http.routers.nginxs.rule=Host(`me.example.com`)"
        - "traefik.http.routers.nginxs.rule=PathPrefix(`/`) || HOST(`nginx.tmktmk.domdom.burger`)"
        - "traefik.http.services.nginxs.loadbalancer.server.port=80"
    networks:
      - test_proxy


networks:
  test_proxy:
    external: true