version: "3.4"

services:
  traefiks:
    image: traefik:latest
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--providers.docker.swarmMode=true"
      - "--api.insecure=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=test_proxy"
    ports:
      - target: 80
        published: 80
      - target: 8080
        published: 8080
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - test_proxy

networks:
  test_proxy:
    external: true
